# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  eb: circleci/aws-elastic-beanstalk@2.0.1

commands:
  build-image: aws-ecr/build-image

workflows:
  build:
    jobs:
      - aws-ecr/build-and-push-image:
          context:
            - CIRCLECI-TEST
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          create-repo: false
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: ./
          region: AWS_DEFAULT_REGION
          repo: circleci-test
          skip-when-tags-exist: false
          tag: $CIRCLE_SHA1
          # filters:
          #   branches:
          #     only:
          #       - dev
